### 예약 생성
POST http://localhost:8084/v1/reservations
Content-Type: application/json

{
  "storeId": "d290f1ee-6c54-4b01-90e6-d701748f0851",
  "reservationDate": "2025-12-16",
  "reservationTime": "18:30:00",
  "headcount": 3
}

### 예약 인원수 변경
PATCH http://localhost:8084/v1/reservations/f3fa09c2-eb41-4421-9cf8-a8e5cb156775
Content-Type: application/json

{
  "headcount": 4
}

### 예약 취소
PATCH http://localhost:8084/v1/reservations/f3fa09c2-eb41-4421-9cf8-a8e5cb156775/cancel

### 예약 노쇼(오너)
PATCH http://localhost:8084/v1/reservations/owner/f3fa09c2-eb41-4421-9cf8-a8e5cb156775/noshow

### 예약 조회(고객)
GET http://localhost:8084/v1/reservations

### 예약 조회(오너)
GET http://localhost:8084/v1/reservations/owner?storeId=d290f1ee-6c54-4b01-90e6-d701748f0851
