### 리뷰 생성
POST http://localhost:19091/v1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDU0NTkyNi1kZjUyLTRkOWItYmUzZC02ZWE4MTlmZGRhNjciLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NjY1NTI1NTMsImV4cCI6MTc2NjYzODk1M30._TPJ-ZHLlVzad_CoPt1y0ia4zEHQqBAzBIQT5-zzM8Q
Content-Type: application/json

{
  "reservationId": "f0fe40b3-a592-4061-b506-fa69c573788b",
  "rating" : 5.0,
  "content" : "정말 맛있습니다~! 강추"
}

### 리뷰 단건 조회                       reviewId
GET http://localhost:19091/v1/reviews/0d279f8c-fa9d-4a14-8fce-56aff88b9931
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDU0NTkyNi1kZjUyLTRkOWItYmUzZC02ZWE4MTlmZGRhNjciLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NjY1NTI1NTMsImV4cCI6MTc2NjYzODk1M30._TPJ-ZHLlVzad_CoPt1y0ia4zEHQqBAzBIQT5-zzM8Q
Content-Type: application/json

### 리뷰 수정                             reviewId
PATCH http://localhost:19091/v1/reviews/0d279f8c-fa9d-4a14-8fce-56aff88b9931
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDU0NTkyNi1kZjUyLTRkOWItYmUzZC02ZWE4MTlmZGRhNjciLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NjY1NTI1NTMsImV4cCI6MTc2NjYzODk1M30._TPJ-ZHLlVzad_CoPt1y0ia4zEHQqBAzBIQT5-zzM8Q
Content-Type: application/json

{
  "rating" : 1.0,
  "content" : "이딴것도 음식이라고 쳐파는거냐?"
}

### 리뷰 삭제                              reviewId
DELETE http://localhost:19091/v1/reviews/0d279f8c-fa9d-4a14-8fce-56aff88b9931
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDU0NTkyNi1kZjUyLTRkOWItYmUzZC02ZWE4MTlmZGRhNjciLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NjY1NTI1NTMsImV4cCI6MTc2NjYzODk1M30._TPJ-ZHLlVzad_CoPt1y0ia4zEHQqBAzBIQT5-zzM8Q
Content-Type: application/json

#### 가게에 작성된 리뷰 목록 조회           storeId
GET http://localhost:19091/v1/stores/8f3c6a5e-9e84-4c3f-9b80-7c2dd1a4e2c1/reviews?sortBy=RATING_HIGH
Content-Type: application/json

### 내가 작성한 리뷰 목록 조회
GET http://localhost:19091/v1/users/me/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NDU0NTkyNi1kZjUyLTRkOWItYmUzZC02ZWE4MTlmZGRhNjciLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NjY1NTI1NTMsImV4cCI6MTc2NjYzODk1M30._TPJ-ZHLlVzad_CoPt1y0ia4zEHQqBAzBIQT5-zzM8Q
Content-Type: application/json

### 회원 가입
POST http://localhost:19091/v1/auth/signup
Content-Type: application/json

{
  "email": "customer111@test.com",
  "password": "Test1234!",
  "username": "홍길동",
  "phoneNumber": "01034567890"
}

### 로그인
POST http://localhost:19091/v1/auth/login
Content-Type: application/json

{
  "email": "customer111@test.com",
  "password": "Test1234!"
}

