server:
  port: 8085

spring:
  application:
    name: hot-reservation-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka
