server:
  port: 8084

spring:
  application:
    name: reservation-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka
