server:
  port: 8081

spring:
  application:
    name: user-service

  # ✅ 데이터베이스 설정 (환경변수 처리)
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:} # env 파일화
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# ✅ JWT 설정 (환경변수 처리)
jwt:
  secret: ${JWT_SECRET:} # env 파일화
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:86400000}     # 24시간
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7일

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka}
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

# 로깅 설정
logging:
  level:
    org.springframework.security: INFO
    com.tablekok.user_service: INFO
    org.hibernate.SQL: DEBUG

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
